# Generated by Django 4.0.5 on 2022-07-27 20:38

import challenges.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, null=True, validators=[challenges.validators.validatePassword]),
        ),
    ]
