# Generated by Django 4.0.5 on 2022-07-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_address_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='challenges.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.creditcard'),
        ),
    ]
